[project]
name = "login-in-web-app-with-tg-bot"
version = "0.1.0"
description = "At start it's simple app to show user data from Telegram by using bot"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "uv>=0.9.18",
]

[tool.uv.workspace]
members = [
    "app",
    "bot",
]

[tool.mypy]
plugins = [
  "pydantic.mypy"
]

follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true

disallow_untyped_defs = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true