[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.22.0",
    "aiosqlite>=0.22.1",
    "alembic>=1.18.1",
    "fastapi>=0.116.1",
    "fastapi-jsonapi>=3.0.0",
    "fastapi-users>=15.0.3",
    "jinja2>=3.1.6",
    "jwt>=1.4.0",
    "pydantic-settings>=2.10.1",
    "pydantic[email]>=2.11.7",
    "sqlalchemy[asyncio]>=2.0.43",
    "uvicorn>=0.35.0",
]
